name: SkalkaNetherowa
version: 1.2
main: pl.twojserwer.skalki.SkalkaNetherowa
api-version: "1.20"
description: Autorskie skalki netherowe na Paper 1.20.4
commands:
  skalka:
    description: Zarzadzanie skalkami netherowymi
    permission: skalka.admin
